### ISSUE TITLE
Remix + Hardhat

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-project#1011]
- [ ] #1007 hardhat console logs in remix
- [ ] #1008 Hardhat and Remix compilationResult
- [ ] #1010 Hardhat commands in Remix terminal
