### ISSUE TITLE
Monaco Editor improvements

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-project#1793]
- [ ] Code snippets (https://github.com/ethereum/remix-project/issues/233)
- [ ] mark vars according to type if possible (https://github.com/ethereum/remix-project/issues/169)
- [ ] make obvious for user that she/he is in read only mode (https://github.com/ethereum/remix-project/issues/206)

**Comment by Astilen** [comment]
Yes we need different colors for each different element in the code, the new theme has less visual cues and takes more time to read.

**Comment by Astilen** [comment]
![1](https://user-images.githubusercontent.com/23420185/143427932-855cb657-feea-4716-b955-2de4d58ce479.png)
Here is a picture of code that was easy to read, and a screenshot of how the code looks now:
Issues: 
1)  Function names were green, data coming in the function was orange, and the code logic was gray, but now ALL of them are gray. 
2) for, return etc,  were orange and variables were blue,  now ALL are blue.

If you simply put a theme with different colors for these code elements, this will make reading code much more efficient.
Thank you :D

**Comment by LianaHus** [comment]
@Astilen  please check put new release. we updated some kewords/colors there.

**Comment by jonabislimi** [comment]
Will remix ever return to its original format? I find its become pretty bothersome to use. In the past colors were very easy to read and understand, and now it looks a bit clumped up. Is this a permanent change or will it go back? thank you for your answers
