### ISSUE TITLE
Solidity Plugin improvements

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-project#1794]
- [ ] Show compiler license (https://github.com/ethereum/remix-project/issues/247)
- [ ] Show "compilation details" in a tab (https://github.com/ethereum/remix-project/issues/259)
- [ ] Autocomplete for solidity (https://github.com/ethereum/remix-project/issues/199)

**Comment by dev-tom-0108** [comment]
Yes, the functions you mentioned here are in remix.org.
I think the remix is the best program to compile and deploy the smart contract.
After that, I hope you are going well and discuss with me about that.
