### ISSUE TITLE
Debugger improvements

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-project#1795]
- [ ] "Loaded address" does not always follow inter-contract calls  (https://github.com/ethereum/remix-project/issues/247)
- [ ]  Mark call types on slider (https://github.com/ethereum/remix-project/issues/170)
- [ ] Storage debugging should have an option to load every key  (https://github.com/ethereum/remix-project/issues/250)
- [ ] to force Remix to use a specific solidity source code (https://github.com/ethereum/remix-project/issues/149)
