### ISSUE TITLE
File Explorer improvements

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-project#1796]
- [ ] Open combined-json files from the File Explorer (https://github.com/ethereum/remix-project/issues/148)
- [ ] Add delete and rename files with "delete" and F2 keys (https://github.com/ethereum/remix-project/issues/258)
- [ ] Sort items in folder (https://github.com/ethereum/remix-project/issues/123)
- [ ] add "copy file name" to readonly(ipfs/swarm) files context menu (https://github.com/ethereum/remix-project/issues/333)
- [ ] add a display name option for ipfs/swarm file (https://github.com/ethereum/remix-project/issues/226)
