### ISSUE TITLE
JS integration

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-project#2228]
partially_fix https://github.com/ethereum/remix-project/pull/2234

 - [x] import with `import`
 - [x] run typescript files
 - [x] autocompletion for : local files, ethers, web3, remix plugin
