### ISSUE TITLE
File Explorer Improvements

### ISSUE THREAD

**Issue by joeizang** [ethereum/remix-project#4150]
- [ ] DRAG AND DROP FILES FROM WITHIN AND OUTSIDE FILE EXPLORER - 
dragging files from outside file explorer means uploading files from the local file system. (Feature)
- [ ] FILE EXPLORER MULTI SELECTION OF FILES (Feature)
- [ ] SEARCH FOR FILES OR FOLDERS IN PLACE - when the cursor is not focused on the editor, any letter pushed on the keyboard results in a search of files in file explorer (Feature)
- [ ] OUTLINE AND TIMELINE SECTIONS AT THE BOTTOM OF FILE EXPLORER - Outline section shows every symbol in the currently active editor. It offers you the ability to sort by type of symbol. So it shows variables, functions and other types of symbols. Timeline section shows files based on age. (Feature)
- [ ] FILE EXPLORER CUSTOMIZATIONS ENABLED BY SETTINGS IN THE IDE.(MOVE FILE EXPLORER TO EITHER THE LEFT OR RIGHT ETC) (Feature)
- [ ] FILE EXPLORER RENAME FILE ON ENTER KEY (Feature)
- [ ] INCREASE STATEFULNESS OF FILE EXPLORER - This is keeping track of certain adjustments that we introduce to the file explorer. Example would be the width of the file explorer or different highlights of selected files depending on what is selected. (Feature)
- [ ] SPLIT FE INTO SECTIONS

- [ ] Folder called browser cannot be created in file explorer https://github.com/ethereum/remix-project/issues/3172 (BUG FE)
- [ ] Add more capabilities in the context menu. Like vyper compile and other core features. https://github.com/ethereum/remix-project/issues/1631 (CONTEXT MENU)
- [ ] Ability to undo actions in FE and redo. It was closed with no real reason stated https://github.com/ethereum/remix-project/issues/2658 (UNDO & REDO)
- [ ] Ability to import or upload folders localFS, git, ipfs and https. https://github.com/ethereum/remix-project/issues/1641 (FOLDER IMPORTS)
- [ ] When connected with remixd to localhost, if file is imported from hometab using either git, ipfs, a blank workspace is created with the file not in localhost. https://github.com/ethereum/remix-project/issues/3185 (FE & HOMETAB)
- [ ] Creation of workspaces should still be possible even when on localhost. https://github.com/ethereum/remix-project/issues/3207 (REMIXD & FE)
- [ ] When a workspace is created from a template on the hometab, the workspace isn’t customizable. https://github.com/ethereum/remix-project/issues/3242 (HOMETAB & FE)
- [ ] Opening relative files from path in editor results in console error cannot read/write to path outside workspace https://github.com/ethereum/remix-project/issues/3256 (FE & EDITOR)
- [ ] Shortkeys to some entries in the context menu https://github.com/ethereum/remix-project/issues/3309 (FE CONTEXT MENU)
- [ ] FE DUPLICATE FILES SHOULD BE PREFIXED WITH NUMBER https://github.com/ethereum/remix-project/issues/3456
- [ ] FE GIST MULTISELECT FILES Multiple files, when selected, should be published to a gist https://github.com/ethereum/remix-project/issues/851
- [ ] Deeper dgit integration with FE FE GIT INTEGRATION https://github.com/ethereum/remix-project/issues/2225
- [ ] FE should have hidden files and folders https://github.com/ethereum/remix-project/issues/3336 (FE HIDDEN FILES & FOLDERS)
- [ ] FE should have readonly files and filders https://github.com/ethereum/remix-project/issues/3335 (FE READONLY FILES)
- [ ] Missing files https://github.com/ethereum/remix-project/issues/3280
