### ISSUE TITLE
Matomo-ification of the Circom Plugin

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#4284]
Make sure that the Circom plugin is hooked up into Matomo - including:
- [x] Activation of the plugin (via the plugin manager or via URL)
- [x] The compile button
- [x] The compute witness button
- [x] The generate r1cs button

and anything else you can think of. 
```[tasklist]
### Tasks
```
