### ISSUE TITLE
Home tab refactoring

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-project#44]
- [x] Add new features (https://github.com/ethereum/remix-ide/issues/2451)

- [x] Make links more visible (https://github.com/ethereum/remix-ide/issues/2452)
- [x] Add tweets and maybe blogposts (https://github.com/ethereum/remix-ide/issues/2892)
- [x] Add a website link (https://github.com/ethereum/remix-ide/issues/2729)

**Comment by Aniket-Engg** [comment]
- [ ] https://github.com/ethereum/remix-project/issues/595
- [ ] https://github.com/ethereum/remix-project/issues/570
