### ISSUE TITLE
Improvements to data shown when 'listen to network' is checked

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-project#450]
- [x] Show transaction in sequence according to `txIndex`
- [x] `to` address is shown twice consecutively
- [x] Transaction hash is shown twice under different fields `transaction hash` & `hash`

Here is the related screenshot:
<img width="867" alt="listentonwIssue" src="https://user-images.githubusercontent.com/30843294/94242687-0e35a380-ff34-11ea-8ab0-2550a9a330be.png">
