### ISSUE TITLE
Solidity Unit Testing Plugin Enhancements

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-project#47]
- [ ] Improve contract name of generated sample test file ethereum/remix-ide#2758 
- [ ] Discuss and decide where should generated sample test file reside in file explorer ethereum/remix-ide#2765 
- [ ] Add custom transaction context tests for 'Solidity Unit Testing' ethereum/remix-project#26 
- [ ] When test results are: 
```
totalPassing: 0
totalFailing: 0
totalTime: 0
```
On UI, it shows PASS without any tests summary
