### ISSUE TITLE
Solidity Static Analysis Plugin Enhancements

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-project#48]
- [ ] add a checkbox to checkAll to each categorie ethereum/remix-ide#2772 
- [x] highlight source location ethereum/remix-ide#2808 
- [ ] show expandable modules and not accordion ethereum/remix-ide#2810 
- [x] add module title to warnings ethereum/remix-ide#2820
- [ ] Download analysis report ethereum/remix-ide#2874

**Comment by Aniket-Engg** [comment]
Make improvements to handle this case: https://github.com/ethereum/remix/issues/857
