### ISSUE TITLE
remix-plugin api usage in IDE

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-project#667]
- [x] ~~use `this.emit` instead of `this.events.emit` (#2210 -> #117)~~
- [x] don't call pluginManager API directly (`pluginManager.activatePlugin('...')` -> `this.call('manager', 'activatePlugin', '...')`) #666
- [x] ~~every service should be isolated into a plugin(tabProxy, )~~ done during move to react
- [x] ~~each service should only be able to communicate with each other through the plugin API~~ done during move to react

**Comment by yann300** [comment]
@bunsenstraat 
Tagging you in this issue, the last 2 points are actually what you did with the compiler core plugins.
