### ISSUE TITLE
File explorer improvements

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-project#671]
- [x] Add access to the context menu for plugins (#397)
- [x] Finish (https://github.com/ethereum/remix-project/issues/55)
- [x] cop/past/cut
- [x] Drag and Drop
- [x] copying and pasting between workspaces is not possible (https://github.com/ethereum/remix-project/issues/1317)
- [x] serach in files (https://github.com/ethereum/remix-project/issues/1630)
- [x] Add Publish to gist to context menu of each folder (https://github.com/ethereum/remix-project/issues/801)
- [x] Publish to GIST with a right click on multi selected files (https://github.com/ethereum/remix-project/issues/851)
- [x] Ask to include default set of files and folders for new workspace (https://github.com/ethereum/remix-project/issues/1102)
- [x] multiselection in FE (https://github.com/ethereum/remix-project/issues/1131)
- [x] Sync Editor and FE for current selected (https://github.com/ethereum/remix-project/issues/1405)
