### ISSUE TITLE
remix-tests/Solidity unit testing plugin Improvements

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-project#673]
- [ ] Custom compiler context for remix-tests CLI (#540 )
- [ ] Dynamic tests generation based on contract (Research needed)
- [ ] Support for logging in test file
- [ ] Enable debugging for unit testing transactions
