### ISSUE TITLE
Interoperability with dev tools like truffle, hardhat etc

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-project#675]
**TRUFFLE**

- [x] Truffle Compilation
- [x] Truffle provider plugin

**HARDHAT**

- [x] Hardhat Compilation for localhost workspace
- [x] Hardhat provider plugin to connect with hardhat node
- [x] Hardhat console.log support
