### ISSUE TITLE
Interoperability with other contract frameworks like openzepplin etc.

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-project#676]
- [ ] Native support to import a file from github repo
- [ ] Support to import even a certain directory from repo
- [ ] Import `interfaces` in the file explorer directly
